import{S as a,N as m}from"./assets/vendor-Sm41FR0M.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const h=[{selector:".characters-swiper",slideClass:"characters-swiper-slide",wrapperClass:"characters-swiper-wrapper"},{selector:".reviews-swiper",slideClass:"reviews-swiper-slide",wrapperClass:"reviews-swiper-wrapper"},{selector:".gallery-swiper",slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",navigation:{nextEl:".custom-navigation .custom-next",prevEl:".custom-navigation .custom-prev"}}],l={};function d(){const n=window.innerWidth;h.forEach(s=>{const o=document.querySelector(s.selector);if(!o)return;const r=s.selector;if(l[r]&&(l[r].destroy(!0,!0),delete l[r]),s.selector===".characters-swiper"){if(n<1439){const e=new a(o,{slidesPerView:1,spaceBetween:10,loop:!0,slideClass:s.slideClass,wrapperClass:s.wrapperClass,direction:"horizontal"});l[r]=e}}else if(s.selector===".reviews-swiper"){if(n<1439){const e=new a(o,{slidesPerView:1,spaceBetween:20,loop:!0,slideClass:s.slideClass,wrapperClass:s.wrapperClass,direction:"horizontal"});l[r]=e}}else if(s.selector===".gallery-swiper"){const e=new a(o,{modules:[m],breakpoints:{374:{slidesPerView:1.2,spaceBetween:20,centeredSlides:!1},1439:{slidesPerView:4,spaceBetween:20,centeredSlides:!1}},loop:!0,slideClass:s.slideClass,wrapperClass:s.wrapperClass,direction:"horizontal",navigation:{nextEl:".custom-navigation .custom-next",prevEl:".custom-navigation .custom-prev"}});l[r]=e}})}document.addEventListener("DOMContentLoaded",d);window.addEventListener("resize",()=>{clearTimeout(window._swiperResizeTimeout),window._swiperResizeTimeout=setTimeout(d,300)});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),s=n.querySelector(".icon"),o=document.querySelector(".modal"),r=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const i=`
<svg width="36" height="24" viewBox="0 0 36 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M0 24V21H36V24H0ZM0 13.5V10.5H36V13.5H0ZM0 3V0H36V3H0Z" fill="#FFF1E0" />
</svg>
    `,u=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#4B3B2B" />
</svg>
    `;n.addEventListener("click",()=>{t=!t,s.innerHTML=t?u:i,t?p():c()}),r.forEach(f=>f.addEventListener("click",()=>{c(),s.innerHTML=i,t=!1})),window.addEventListener("scroll",w);function p(){o.style.display="block"}function c(){o.style.display="none"}function w(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function n(){const r=document.getElementById("site-header");return r?r.offsetHeight:0}function s(r){const e=document.getElementById(r);if(!e)return;const t=n(),i=e.getBoundingClientRect().top+window.pageYOffset-t;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll('a[href^="#"]').forEach(r=>{r.addEventListener("click",function(e){const t=this.getAttribute("href");if(t.startsWith("index.html#")||t.startsWith("http"))return;e.preventDefault();const i=t.substring(1);s(i)})});const o=window.location.hash;if(o){const r=o.substring(1);setTimeout(()=>{s(r)},1e3)}});
//# sourceMappingURL=index.js.map
