import{S as c,N as f}from"./assets/vendor-Sm41FR0M.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const h=[{selector:".characters-swiper",slideClass:"characters-swiper-slide",wrapperClass:"characters-swiper-wrapper"},{selector:".reviews-swiper",slideClass:"reviews-swiper-slide",wrapperClass:"reviews-swiper-wrapper"},{selector:".gallery-swiper",slideClass:"gallery-swiper-slide",wrapperClass:"gallery-swiper-wrapper",navigation:{nextEl:".custom-navigation .custom-next",prevEl:".custom-navigation .custom-prev"}}],l={};function d(){const n=window.innerWidth;h.forEach(t=>{const o=document.querySelector(t.selector);if(!o)return;const r=t.selector;if(l[r]&&(l[r].destroy(!0,!0),delete l[r]),t.selector===".characters-swiper"){if(n<1439){const e=new c(o,{slidesPerView:1,spaceBetween:10,loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal"});l[r]=e}}else if(t.selector===".reviews-swiper"){if(n<1439){const e=new c(o,{slidesPerView:1,spaceBetween:20,loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal"});l[r]=e}}else if(t.selector===".gallery-swiper"){const e=new c(o,{modules:[f],breakpoints:{374:{slidesPerView:1.2,spaceBetween:20,centeredSlides:!1},1439:{slidesPerView:4,spaceBetween:20,centeredSlides:!1}},loop:!0,slideClass:t.slideClass,wrapperClass:t.wrapperClass,direction:"horizontal",navigation:{nextEl:".custom-navigation .custom-next",prevEl:".custom-navigation .custom-prev"}});l[r]=e}})}document.addEventListener("DOMContentLoaded",d);window.addEventListener("resize",()=>{clearTimeout(window._swiperResizeTimeout),window._swiperResizeTimeout=setTimeout(d,300)});document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".menu-button"),t=n.querySelector(".icon"),o=document.querySelector(".modal"),r=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let s=!1;const i=`
<svg width="36" height="24" viewBox="0 0 36 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M0 24V21H36V24H0ZM0 13.5V10.5H36V13.5H0ZM0 3V0H36V3H0Z" fill="#FFF1E0" />
</svg>
    `,p=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#4B3B2B" />
</svg>
    `;n.addEventListener("click",()=>{s=!s,t.innerHTML=s?p:i,s?u():a()}),r.forEach(m=>m.addEventListener("click",()=>{a(),t.innerHTML=i,s=!1})),window.addEventListener("scroll",w);function u(){o.style.display="block"}function a(){o.style.display="none"}function w(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function n(){const r=document.getElementById("site-header");return r?r.offsetHeight:0}function t(r){const e=document.getElementById(r);if(!e)return;const s=n(),i=e.getBoundingClientRect().top+window.pageYOffset-s;window.scrollTo({top:i,behavior:"smooth"})}document.querySelectorAll('a[href^="#"]').forEach(r=>{r.addEventListener("click",function(e){const s=this.getAttribute("href");if(s.startsWith("index.html#")||s.startsWith("http"))return;e.preventDefault();const i=s.substring(1);t(i)})});const o=window.location.hash;if(o){const r=o.substring(1);setTimeout(()=>{t(r)},1e3)}});document.addEventListener("DOMContentLoaded",function(){const n=document.getElementById("cookie-popup"),t=document.getElementById("accept-cookies"),o=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(n.style.display="block"),t.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),n.style.display="none"}),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),n.style.display="none"})});
//# sourceMappingURL=index.js.map
